### ISSUE TITLE
Not working in cms V 2.x It only works with 1.x

### ISSUE THREAD

**Issue by master3395** [ImpetusGames/cms-oauth#1]
Got any idea how to get it working for V2.x?

Update:
Here's the error i get now.
also i recommend moving it from lib into somewere else, since lib is normally not acessable.

Fatal error: Uncaught Hybrid_Exception: You cannot access this page directly. in /home/User/public_html/hybridauth/Hybrid/Endpoint.php:211 Stack trace: #0 /home/User/public_html/hybridauth/Hybrid/Endpoint.php(117): Hybrid_Endpoint->authInit() #1 /home/User/public_html/hybridauth/Hybrid/Endpoint.php(51): Hybrid_Endpoint->processAuthStart() #2 /home/User/public_html/hybridauth/Hybrid/Endpoint.php(72): Hybrid_Endpoint->__construct(Array) #3 /home/User/public_html/hybridauth/index.php(15): Hybrid_Endpoint::process() #4 {main} Next Hybrid_Exception: Endpoint: Error while trying to init Hybrid_Auth: You cannot access this page directly. in /home/User/public_html/hybridauth/Hybrid/Endpoint.php:217 Stack trace: #0 /home/User/public_html/hybridauth/Hybrid/Endpoint.php(117): Hybrid_Endpoint->authInit() #1 /home/User/public_html/hybridauth/Hybrid/Endpoint.php(51): Hybrid_Endpoint->processAuthStart() #2 /home/User/public_html/hybridauth/Hybrid/Endpoint.php(72): Hybrid_Endpoint->_ in /home/User/public_html/hybridauth/Hybrid/Endpoint.php on line 217
– skjul sitert tekst –

mandag 20. juni 2016 13.27.28 UTC+2 skrev Kim Skorgenes følgende:
Is this working in the latest V2.1.4 of CMSMS?
I seem to get this "You must not call this script directly without parameters."
I have filled out the parameters in config.

**Comment by haimat** [comment]
Hey, thanks for your feedback.
Unfortunately at the moment we have no plans for V2.
